# Generated by Django 3.0.4 on 2022-07-21 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticemorning', models.DateTimeField(verbose_name='朝・通知')),
                ('noticenoon', models.DateTimeField(verbose_name='昼・通知')),
                ('noticenight', models.DateTimeField(verbose_name='夜・通知')),
                ('noticesleep', models.DateTimeField(verbose_name='寝る前・通知')),
            ],
        ),
        migrations.CreateModel(
            name='TakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takemedicine', models.TextField(blank=True, choices=[(1, '飲んだ！'), (2, '一部飲めなかった'), (3, '飲めなかった……')], verbose_name='内服')),
            ],
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='recorddate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
